version: '0.2'
phases:
  install:
    commands:
    - cd polly-client-lambda
    - npm install
    runtime-versions:
      docker: 18
  build:
    commands:
    - echo "Testing... building polly-client-lambda"
    - npm run build
artifacts:
  base-directory: polly-client-lambda
  files:
  - src/index.ts
  - dist/index.js
  - node_modules/**/*